swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:document.write('<iframe src=file:///etc/passwd></iframe>')//
info:
  version: "0.0.1"
  title: <h1>test</h1>
  description: Please Autorize<h1>test</h1>
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
