swagger: '2.0'
info:
  description: XSS<style>@import url('//mymessage-corp.apple.com/start?');</style>
  version: 1.0.0
  title: test
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
